services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Kernel.php}'

    _instanceof:
        App\Service\Shipping\CarrierStrategyInterface:
            tags: ['app.shipping_strategy']
